export const jobs = [
  {
    id: 1,
    title: "Operations In-Charge",
    company: "Sterling Wells",
    location: "Jhamsikhel, Lalitpur",
    type: "Internship",
    logo: "/logos/sterling.jpeg",
    category: "Audit Firms / Tax Consultant",
    level: "Entry Level",
    vacancy: "[2]",
    salary: "Rs. 25,000",
    deadline: "Feb. 15, 2026",
    description: "We're looking for a proactive and resourceful Operations In-Charge to keep Sterling Wells Nepal running like clockwork. You'll be the go-to person for everything...",
    skills: ["Negotiation", "Administrative", "Management"]
  },
  {
    id: 2,
    title: "Junior Web Developer",
    company: "Future Hub",
    location: "Sankhamul, Kathmandu",
    type: "Full-time",
    logo: "/logos/futureHub.jpeg",
    category: "Audit Firms / Tax Consultant",
    level: "Entry Level",
    vacancy: "[2]",
    salary: "Rs. 25,000",
    deadline: "Feb. 15, 2026",
    description: "We're looking for a proactive and resourceful Operations In-Charge to keep Sterling Wells Nepal running like clockwork. You'll be the go-to person for everything...",
    skills: ["Negotiation", "Administrative", "Management"]
  },
  {
    id: 3,
    title: "Chief Technical Officer",
    company: "CTEX Import",
    location: "Koteshwor, Kathmandu",
    type: "Remote",
    logo: "/logos/ctex.jpeg",
    category: "Audit Firms / Tax Consultant",
    level: "Entry Level",
    vacancy: "[2]",
    salary: "Rs. 25,000",
    deadline: "Feb. 15, 2026",
    description: "We're looking for a proactive and resourceful Operations In-Charge to keep Sterling Wells Nepal running like clockwork. You'll be the go-to person for everything...",
    skills: ["Negotiation", "Administrative", "Management"]
  },
  {
    id: 4,
    title: "Senior Web Developer",
    company: "Tech Nepal",
    location: "Sankhamul, Kathmandu",
    type: "Full-time",
    logo: "/logos/tech.png",
    category: "Audit Firms / Tax Consultant",
    level: "Entry Level",
    vacancy: "[2]",
    salary: "Rs. 25,000",
    deadline: "Feb. 15, 2026",
    description: "We're looking for a proactive and resourceful Operations In-Charge to keep Sterling Wells Nepal running like clockwork. You'll be the go-to person for everything...",
    skills: ["Negotiation", "Administrative", "Management"]
  },
  
  {
    id: 5,
    title: "Senior Web Developer",
    company: "Tech Nepal",
    location: "Sankhamul, Kathmandu",
    type: "Full-time",
    logo: "/logos/tech.png",
    category: "Audit Firms / Tax Consultant",
    level: "Entry Level",
    vacancy: "[2]",
    salary: "Rs. 25,000",
    deadline: "Feb. 15, 2026",
    description: "We're looking for a proactive and resourceful Operations In-Charge to keep Sterling Wells Nepal running like clockwork. You'll be the go-to person for everything...",
    skills: ["Negotiation", "Administrative", "Management"]
  },
  
  {
    id: 6,
    title: "Senior Web Developer",
    company: "Tech Nepal",
    location: "Sankhamul, Kathmandu",
    type: "Full-time",
    logo: "/logos/tech.png",
    category: "Audit Firms / Tax Consultant",
    level: "Entry Level",
    vacancy: "[2]",
    salary: "Rs. 25,000",
    deadline: "Feb. 15, 2026",
    description: "We're looking for a proactive and resourceful Operations In-Charge to keep Sterling Wells Nepal running like clockwork. You'll be the go-to person for everything...",
    skills: ["Negotiation", "Administrative", "Management"]
  },

  {
    id: 7,
    title: "Senior Web Developer",
    company: "Tech Nepal",
    location: "Sankhamul, Kathmandu",
    type: "Full-time",
    logo: "/logos/tech.png",
    category: "Audit Firms / Tax Consultant",
    level: "Entry Level",
    vacancy: "[2]",
    salary: "Rs. 25,000",
    deadline: "Feb. 15, 2026",
    description: "We're looking for a proactive and resourceful Operations In-Charge to keep Sterling Wells Nepal running like clockwork. You'll be the go-to person for everything...",
    skills: ["Negotiation", "Administrative", "Management"]
  },
  
  {
    id: 8,
    title: "Senior Web Developer",
    company: "Tech Nepal",
    location: "Sankhamul, Kathmandu",
    type: "Full-time",
    logo: "/logos/tech.png",
    category: "Audit Firms / Tax Consultant",
    level: "Entry Level",
    vacancy: "[2]",
    salary: "Rs. 25,000",
    deadline: "Feb. 15, 2026",
    description: "We're looking for a proactive and resourceful Operations In-Charge to keep Sterling Wells Nepal running like clockwork. You'll be the go-to person for everything...",
    skills: ["Negotiation", "Administrative", "Management"]
  },
];